{"name":"infiniteLoopTest","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"\nExpected exception of type class java.lang.NumberFormatException but got org.testng.internal.thread.ThreadTimeoutException: Method com.selenium.testng.ExceptionTimeOutTest.infiniteLoopTest() didn't finish within the time-out 2000","trace":"org.testng.TestException: \nExpected exception of type class java.lang.NumberFormatException but got org.testng.internal.thread.ThreadTimeoutException: Method com.selenium.testng.ExceptionTimeOutTest.infiniteLoopTest() didn't finish within the time-out 2000\n\tat org.testng.internal.ExpectedExceptionsHolder.wrongException(ExpectedExceptionsHolder.java:68)\n\tat org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:739)\n\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:634)\n\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)\n\tat org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)\n\tat org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)\n\tat org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1541)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:794)\n\tat org.testng.TestRunner.run(TestRunner.java:596)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:377)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:276)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1134)\n\tat org.testng.TestNG.runSuites(TestNG.java:1063)\n\tat org.testng.TestNG.run(TestNG.java:1031)\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)\nCaused by: org.testng.internal.thread.ThreadTimeoutException: Method com.selenium.testng.ExceptionTimeOutTest.infiniteLoopTest() didn't finish within the time-out 2000\n\tat org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:384)\n\tat org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:283)\n\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:604)\n\t... 21 more\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1628886487463,"stop":1628886489479,"uuid":"7dcf29ac-1f43-4cd1-b5d8-f5c573b75312","historyId":"dc97f58499b702ed9a9fd09b135db442","fullName":"com.selenium.testng.ExceptionTimeOutTest.infiniteLoopTest","labels":[{"name":"package","value":"com.selenium.testng.ExceptionTimeOutTest"},{"name":"testClass","value":"com.selenium.testng.ExceptionTimeOutTest"},{"name":"testMethod","value":"infiniteLoopTest"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"TestNG"},{"name":"subSuite","value":"com.selenium.testng.ExceptionTimeOutTest"},{"name":"host","value":"Neals-MacBook-Pro.local"},{"name":"thread","value":"3383@Neals-MacBook-Pro.local.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[]}